# Generated by Django 4.2.2 on 2023-07-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_heartratezone_minimum_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartratezone',
            name='maximum_heart_rate',
            field=models.IntegerField(default=0),
        ),
    ]
