# Generated by Django 4.2.2 on 2023-07-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_heartratezone_maximum_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='os_version',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='vendor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
