# Generated by Django 4.2.2 on 2023-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_origin_os_version_origin_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='dehydration_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time_timezone_offset',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plausible',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time_timezone_offset',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subjective_feeling',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tracking_method',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_perceived_end_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_perceived_start_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fastestsegment',
            name='distance',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fastestsegment',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fastestsegment',
            name='started_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='average',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='maximum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='trace_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='heartratezone',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartratezone',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartratezone',
            name='maximum_heart_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='heartratezone',
            name='minimum_heart_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='heartratezone',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='initialvalues',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='initialvalues',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='initialvalues',
            name='end_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='initialvalues',
            name='pause',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='initialvalues',
            name='sport_type',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='initialvalues',
            name='start_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='encoded_trace',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='start_latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='start_longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='trace_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='device_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='average_step_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='average_step_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='maximum_step_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='total_steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackmetrics',
            name='average_pace',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trackmetrics',
            name='average_speed',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackmetrics',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackmetrics',
            name='elevation_gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackmetrics',
            name='elevation_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackmetrics',
            name='max_speed',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='conditions',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
