# Generated by Django 4.2.2 on 2023-08-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_activity_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.activity')),
                ('id', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
