# Generated by Django 4.2.2 on 2023-10-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
